@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Junior da Silva",
    "email": "teste@gmail.com",
    "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "ismaeljunior1508@gmail.com",
    "password": "123456"
}

### 

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova Pergunta 2",
    "content": "Conteudo da Pergunta"
}

###

# @name fetch_listen_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

